# Generated by Django 2.1.7 on 2019-02-18 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteproductividad',
            name='create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteproductividad',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
