# Generated by Django 2.1.7 on 2019-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_auto_20190218_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteproductividad',
            name='gasolina_dia',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto de Gasolina del día'),
        ),
        migrations.AddField(
            model_name='reporteproductividad',
            name='horas_conexion',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas de Conexión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteproductividad',
            name='kilometros_dia',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometros recorridos del día'),
        ),
        migrations.AddField(
            model_name='reporteproductividad',
            name='monto_facturado',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto Facturado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteproductividad',
            name='numero_viajes',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Viajes'),
            preserve_default=False,
        ),
    ]
