# Generated by Django 2.1.7 on 2019-02-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_auto_20190218_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteproductividad',
            options={'verbose_name_plural': 'ReportesProductividades'},
        ),
        migrations.AlterField(
            model_name='reporteproductividad',
            name='placa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_site.Placa'),
        ),
    ]
