# Generated by Django 2.1.7 on 2019-03-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_auto_20190223_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='placa',
            field=models.CharField(max_length=6, verbose_name='Placa que reportas'),
        ),
    ]
