# Generated by Django 2.1.7 on 2019-03-27 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0007_reporteproductividad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteproductividad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL),
        ),
    ]
