# Generated by Django 2.1.7 on 2019-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0009_auto_20190327_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteproductividad',
            name='monto_facturado',
        ),
        migrations.AddField(
            model_name='reporteproductividad',
            name='monto_facturado_beat',
            field=models.PositiveIntegerField(default=0, verbose_name='Facturación Beat (sin bonos, sin decimales)'),
        ),
        migrations.AddField(
            model_name='reporteproductividad',
            name='monto_facturado_cabify',
            field=models.PositiveIntegerField(default=0, verbose_name='Facturación Cabify (sin bonos, sin decimales)'),
        ),
        migrations.AddField(
            model_name='reporteproductividad',
            name='monto_facturado_didi',
            field=models.PositiveIntegerField(default=0, verbose_name='Facturación Didi (sin bonos, sin decimales)'),
        ),
        migrations.AddField(
            model_name='reporteproductividad',
            name='monto_facturado_uber',
            field=models.PositiveIntegerField(default=0, verbose_name='Facturación Uber (sin bonos, sin decimales)'),
        ),
        migrations.AlterField(
            model_name='reporteproductividad',
            name='numero_viajes',
            field=models.PositiveIntegerField(verbose_name='Cantidad de Viajes Totales del Día'),
        ),
    ]
