# Generated by Django 2.1.7 on 2019-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0010_auto_20190327_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteproductividad',
            name='horas_conexion',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas de Conexión'),
        ),
        migrations.AlterField(
            model_name='reporteproductividad',
            name='numero_viajes',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Viajes Totales del Día'),
        ),
    ]
