# Generated by Django 2.1.7 on 2019-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0011_auto_20190327_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteproductividad',
            name='total_facturado',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
