# Generated by Django 2.1.7 on 2019-03-27 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0012_reporteproductividad_total_facturado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteproductividad',
            name='horas_conexion',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Horas de Conexión'),
        ),
    ]
