# Generated by Django 2.1.7 on 2019-03-27 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0013_auto_20190327_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteproductividad',
            name='gasolina_dia',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Monto de Gasolina del día'),
        ),
        migrations.AlterField(
            model_name='reporteproductividad',
            name='kilometros_dia',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Kilometros recorridos del día'),
        ),
        migrations.AlterField(
            model_name='reporteproductividad',
            name='monto_facturado_beat',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='Facturación Beat (sin bonos, sin decimales)'),
        ),
        migrations.AlterField(
            model_name='reporteproductividad',
            name='monto_facturado_cabify',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='Facturación Cabify (sin bonos, sin decimales)'),
        ),
        migrations.AlterField(
            model_name='reporteproductividad',
            name='monto_facturado_didi',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='Facturación Didi (sin bonos, sin decimales)'),
        ),
        migrations.AlterField(
            model_name='reporteproductividad',
            name='monto_facturado_uber',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='Facturación Uber (sin bonos, sin decimales)'),
        ),
    ]
