# Generated by Django 2.1.7 on 2019-03-28 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0014_auto_20190327_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteproductividad',
            name='gasolina_dia',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1200)], verbose_name='Monto de Gasolina del día'),
        ),
    ]
