# Generated by Django 2.1.7 on 2019-03-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0015_auto_20190328_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteproductividad',
            options={'ordering': ('-create',), 'verbose_name_plural': 'ReportesProductividades'},
        ),
    ]
