# Generated by Django 2.1.7 on 2019-04-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0018_auto_20190330_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteproductividad',
            options={'ordering': ('-fecha_reporte',), 'verbose_name_plural': 'ReportesProductividades'},
        ),
    ]
