# Generated by Django 2.1.7 on 2019-04-02 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0019_auto_20190402_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteproductividad',
            name='numero_viajes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Cantidad de Viajes Totales del Día'),
        ),
    ]
