# Generated by Django 2.2.1 on 2019-08-02 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0020_auto_20190402_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteproductividad',
            name='cobros_efectivo',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='Cobros en Efectivo (sin decimales)'),
        ),
    ]
